### PR TITLE
Changed title and abstract of Nick Carneiro's talk.

### PR DESCRIPTION
**Pull request by NickCarneiro**
This will be more exciting than the Closure talk.

### CODE REVIEW

**Comment by JacksonTian** [comment]
Nick, are sure change the title?

**Comment by NickCarneiro** [comment]
Yes, I would like to change the title.

Did I miss any occurrences of the title?

**Comment by JacksonTian** [comment]
Ok. The html file is generated by script, so need change the origin JSON file. I will help you change the title, and publish it. This issue will be closed later.

**Comment by NickCarneiro** [comment]
Ah, I didn't see the src folder. Sorry.

**Comment by JacksonTian** [comment]
Changed for you. visit http://jingjs.org/schedule.html please.

**Pull request closed without merging**
